//Import dependencies and components. And images.
import { useState } from 'react';
import NZ from "../Images/NZ/NZ.png"
import Auckland from "../Images/NZ/Auckland.png"
import Bay_of_Plenty from "../Images/NZ/Bay of Plenty.png"
import Cantebury from "../Images/NZ/Cantebury.png"
import Gisborne from "../Images/NZ/Gisborne.png"
import Hawke from "../Images/NZ/Hawke's Bay.png"
import Manawatuu from "../Images/NZ/Manawatuu-Wanganui.png"
import Malborough from "../Images/NZ/Melborough.png"
import Nelson from "../Images/NZ/Nelson.png"
import Northland from "../Images/NZ/Northland.png"
import Otago from "../Images/NZ/Otago.png"
import Southland from "../Images/NZ/Southland.png"
import Taranaki from "../Images/NZ/Taranaki.png"
import Tasman from "../Images/NZ/Tasman.png"
import Waikato from "../Images/NZ/Waikato.png"
import Wellington from "../Images/NZ/Wellington.png"
import West_Coast from "../Images/NZ/Westcoast.png"

//--------------------------------------------------------
// Demo 2 is a map displaying the regions of New Zealand
// Selecting a region displays the store address in that region.

// Demo 2 function
function Demo2() {

  const [displayNZ, setDisplayNZ] = useState(NZ); //By default it displays the regular NZ image which has no regions highlighted.
  const [regionAddress, setRegionAddress] = useState("123 Placeholder Street");
  const [visibleDiv, setVisibleDiv] = useState("none"); //The box showing the address is invisible by default.

  const regionClick = (region) => {
    setDisplayNZ(region);
    setVisibleDiv("block") // When the map is clicked the box to show the address appears.

    switch (region) {
      case Auckland:
        setRegionAddress("123 Example Street");
        break;
      case Bay_of_Plenty:
        setRegionAddress("321 Example Road");
        break;
      case Cantebury:
        setRegionAddress("111 Example Street");
        break;
      case Gisborne:
        setRegionAddress("101 Example Road");
        break;
      case Hawke:
        setRegionAddress("1337 Placeholder Street");
        break;
      case Manawatuu:
        setRegionAddress("777 Street Avenue");
        break;
      case Malborough:
        setRegionAddress("1 Number Road");
        break;
      case Nelson:
        setRegionAddress("0 Nonexistent Drive");
        break;
      case Northland:
        setRegionAddress("4 Street Street");
        break;
      case Otago:
        setRegionAddress("5 Street Street");
        break;
      case Southland:
        setRegionAddress("6 Street Street");
        break;
      case Taranaki:
        setRegionAddress("7 Street Street");
        break;
      case Tasman:
        setRegionAddress("8 Street Street");
        break;
      case Waikato:
        setRegionAddress("9 Street Street");
        break;
      case Wellington:
        setRegionAddress("1,000,000 Street Street");
        break;
      case West_Coast:
        setRegionAddress("2 Street Street");
        break;
      default:
        setRegionAddress("oops. Couldn't find store address.")
      
    }
  };


  return (<>
    <div>
      <h3>Our stores</h3>

      {/*Box to show the address of the place */}
      <div style={{border: "2px solid red", display:visibleDiv}} class="col-12 col-lg-4">
        <p>Phone repair shop address:</p>
        <p>{regionAddress}</p>
      </div>

      {/*imagemap of New Zealand */}
      <div id="NZimage" class="col-12 col-lg-8">

      {/*The image is too big for the layout but changing its size breaks the imagemap so I've left it as is. */}
      {/* Image Map Generated by http://www.image-map.net/ */}
      <img src={displayNZ} usemap="#NZmap" alt="Map of NZ regions" />

      <map name="NZmap">
        <area onClick={ () => regionClick(Southland)} target="" alt="Southland" title="Southland" coords="267,488,276,498,288,519,310,528,328,532,345,570,284,604,249,628,233,534" shape="poly" />
        <area onClick={ () => regionClick(Otago)} target="" alt="Otago" title="Otago" coords="398,514,394,525,389,547,349,571,332,536,292,525,276,494,330,486,345,476,364,502" shape="poly" />
        <area onClick={ () => regionClick(Cantebury)} target="" alt="Cantebury" title="Cantebury" coords="404,515,436,499,466,487,504,401,485,392,450,419,427,401,393,445,347,472,356,500" shape="poly" />
        <area onClick={ () => regionClick(West_Coast)} target="" alt="West Coast" title="West Coast" coords="269,487,276,495,328,487,347,473,387,448,416,414,401,407,423,351,406,338" shape="poly" />
        <area onClick={ () => regionClick(Tasman)} target="" alt="Tasman District" title="Tasman District" coords="418,412,405,406,425,349,406,338,430,312,413,317,445,334,456,353" shape="poly" />
        <area onClick={ () => regionClick(Malborough)} target="" alt="Malborough District" title="Malborough District" coords="425,400,447,416,481,391,501,400,508,389,497,370,503,358,484,347,466,369,448,370" shape="poly" />
        <area onClick={ () => regionClick(Wellington)} target="" alt="Wellington" title="Wellington" coords="526,340,542,357,568,346,572,320,543,316" shape="poly" />
        <area onClick={ () => regionClick(Manawatuu)} target="" alt="Manawatuu-Whanganui" title="Manawatuu-Whanganui" coords="541,315,573,323,581,296,558,264,556,229,539,233,537,201,505,217,504,240,515,244,510,266" shape="poly" />
        <area onClick={ () => regionClick(Taranaki)} target="" alt="Taranaki" title="Taranaki" coords="507,271,515,246,505,241,503,218,493,208,462,218,459,248" shape="poly" />
        <area onClick={ () => regionClick(Hawke)} target="" alt="Hawke's Bay" title="Hawke's Bay" coords="583,294,596,246,619,218,600,195,565,209,554,229,557,269" shape="poly" />
        <area onClick={ () => regionClick(Gisborne)} target="" alt="Gisborne District" title="Gisborne District" coords="621,218,637,212,638,191,647,165,625,156,617,183,600,197" shape="poly" />
        <area onClick={ () => regionClick(Bay_of_Plenty)} target="" alt="Bay of Plenty" title="Bay of Plenty" coords="623,156,614,183,599,194,569,208,572,187,543,172,546,151" shape="poly" />
        <area onClick={ () => regionClick(Waikato)} target="" alt="Waikato" title="Waikato" coords="541,232,561,222,575,186,545,172,545,152,533,123,522,119,529,148,512,148,495,175,493,203,505,216,524,199,539,197" shape="poly" />
        <area onClick={ () => regionClick(Nelson)} alt="Nelson" title="Nelson" coords="450,368,465,369,482,346,457,353" shape="poly" />
        <area onClick={ () => regionClick(Auckland)} alt="Auckland" title="Auckland" coords="492,174,510,146,485,113,459,136" shape="poly" />
        <area onClick={ () => regionClick(Northland)} alt="Northland" title="Northland" coords="463,138,484,106,421,81,409,83,427,111" shape="poly" />
      </map>
      </div>


    </div>
  </>)
};

export default Demo2;